### ISSUE TITLE
Xiaomi Cyberdog

### ISSUE THREAD

**Issue by RubSevian** [fan-ziqi/rl_sim2real#1]
Hello, are you going to make a branch for Xiaomi Cyberdog?

**Comment by fan-ziqi** [comment]
No, this project will use Unitree's robot as it is easier to develop

Xiaomi's robots do not provide a complete model and URDF, and the first generation robots are no longer maintained, so there is no need to develop them again

**Comment by RubSevian** [comment]
Hello, I have a question for you, could you connect directly via a black cable to the walking control board on the first generation Cyberdog?

**Comment by fan-ziqi** [comment]
> Hello, I have a question for you, could you connect directly via a black cable to the walking control board on the first generation Cyberdog?

For the first-generation cyberdog reinforcement learning sim2real function package, please refer to the BlindDog development branch at https://github.com/fan-ziqi/rl_sar, which details how to operate it. This repository will be archived. If you have any questions, please contact me by email.
